DESCRIPTION_LABEL_MAP = {
  "person's full name": "NUME_PRENUME",
  "13-digit personal numeric code": "CNP",
  "date of birth": "DATA_NASTERII",
  "gender or sex": "SEX",
  "nationality": "NATIONALITATE",
  "spoken language": "LIMBA_VORBITA",
  "home address": "ADRESA",
  "workplace address": "ADRESA_LUCRU",
  "mobile phone number": "TELEFON_MOBIL",
  "landline phone number": "TELEFON_FIX",
  "email address": "EMAIL",
  "postal code": "COD_POSTAL",
  "city of birth": "ORAS_NASTERE",
  "country of birth": "TARA_NASTERE",
  "profession or job title": "PROFESIE",
  "field of activity or domain": "ACTIVITATE",
  "employer name": "ANGAJATOR",
  "income or salary": "VENIT",
  "marital status": "STARE_CIVILA",
  "education level": "EDUCATIE",
  "IBAN bank account number": "IBAN",
  "bank account number": "CONT_BANCAR",
  "credit or debit card number": "CARD_NUMBER",
  "passport number": "PASAPORT",
  "identity card number": "BULETIN",
  "license or driver's number": "NUMAR_LICENTA",
  "medical insurance number": "ASIGURARE_MEDICALA",
  "blood type": "GRUPA_SANGE",
  "allergies": "ALERGII",
  "medical conditions": "CONDITII_MEDICALE",
  "IP address": "IP_ADDRESS",
  "username": "USERNAME",
  "device identifier": "DEVICE_ID",
  "biometric data": "BIOMETRIC",
  "contract number": "NUMAR_CONTRACT",
  "vehicle license plate": "NUMAR_PLACA",
  "digital account": "CONT_DIGITAL",
  "cryptocurrency wallet": "WALLET_CRYPTO",
  "alternative account number": "NUMAR_CONT_ALT",
  "client segment": "SEGMENT",
  "politically exposed person status": "EXPUS_POLITIC",
  "FATCA compliance status": "STATUT_FATCA"
}