DESCRIPTION_LABEL_MAP = {
  "numele complet al persoanei": "NUME_PRENUME",
  "cod numeric personal din 13 cifre": "CNP",
  "data nașterii": "DATA_NASTERII",
  "gen sau sex": "SEX",
  "naționalitate": "NATIONALITATE",
  "limba vorbită": "LIMBA_VORBITA",
  "adresa de domiciliu": "ADRESA",
  "adresa locului de muncă": "ADRESA_LUCRU",
  "număr de telefon mobil": "TELEFON_MOBIL",
  "număr de telefon fix": "TELEFON_FIX",
  "adresă de email": "EMAIL",
  "cod poștal": "COD_POSTAL",
  "orașul de naștere": "ORAS_NASTERE",
  "țara de naștere": "TARA_NASTERE",
  "profesia sau funcția": "PROFESIE",
  "domeniul de activitate": "ACTIVITATE",
  "numele angajatorului": "ANGAJATOR",
  "venit sau salariu": "VENIT",
  "stare civilă": "STARE_CIVILA",
  "nivel de educație": "EDUCATIE",
  "număr de cont bancar IBAN": "IBAN",
  "număr de cont bancar": "CONT_BANCAR",
  "număr de card de credit sau debit": "CARD_NUMBER",
  "număr de pașaport": "PASAPORT",
  "număr de carte de identitate": "BULETIN",
  "număr de licență sau permis de conducere": "NUMAR_LICENTA",
  "număr de asigurare medicală": "ASIGURARE_MEDICALA",
  "grupă sanguină": "GRUPA_SANGE",
  "alergii": "ALERGII",
  "condiții medicale": "CONDITII_MEDICALE",
  "adresă IP": "IP_ADDRESS",
  "nume de utilizator": "USERNAME",
  "identificator al dispozitivului": "DEVICE_ID",
  "date biometrice": "BIOMETRIC",
  "număr de contract": "NUMAR_CONTRACT",
  "număr de înmatriculare vehicul": "NUMAR_PLACA",
  "cont digital": "CONT_DIGITAL",
  "portofel de criptomonede": "WALLET_CRYPTO",
  "număr de cont alternativ": "NUMAR_CONT_ALT",
  "segment client": "SEGMENT",
  "statut persoană expusă politic": "EXPUS_POLITIC",
  "statut conformitate FATCA": "STATUT_FATCA"
}
